// Generated by CoffeeScript 1.7.1
var stopWatch;

stopWatch = (function() {
  var initialize, running;

  function stopWatch() {}

  running = '';

  initialize = function() {
    return running = false;
  };

  return stopWatch;

})();
